### ISSUE TITLE
download data script

### ISSUE THREAD

**Issue by hsmohammed** [UBC-MDS/DSCI_522_Group_34#35]
Add instructions to the README about how to use the download data function and what arguments to provide.

**Comment by KangboLu** [comment]
@hsmohammed What do we need to add to README? 
We have already included the Usage for milestone 2. 
Are you referring to Milestone 1? Milestone 1 doesn't require us to do it in the requirement?
Proof of milestone 1 doesn't require the usage section.
![image](https://user-images.githubusercontent.com/17485959/100495351-cf1b0d00-3185-11eb-8d80-e02bbfe7ce31.png)
![image](https://user-images.githubusercontent.com/17485959/100495353-d3472a80-3185-11eb-8589-e1e5e502c113.png)

The issue is irrelevant to the current state of the repo.
