### ISSUE TITLE
Peer Review Feedback (from Sakshi Jain)

### ISSUE THREAD

**Issue by hellosakshi** [UBC-MDS/DSCI_522_Group_34#69]
Hello Team 34,

I am sorry for the late review. 

I like reading your report and organization of Git repo. It's very clean. My feedback is below:

1. Code:
- The makefiles are well written.
- All codes are working properly and are all are readable.
- In the dependency section, it might be nice to include all the dependencies in a yaml file as it will make the process of - reproducing the environment easier.

2 Analysis and reasoning: Figure 1 in the report. I would suggest that to explain violin plot. A violin plot is difficult to read if the reader is not from the statistical world. To attract bigger audience size, I will suggest explaining  the blue dot and how to read it. 

I don't think I have much to add in terms of feedback points. On the flip side, I learnt a lot after looking at your project.

**Comment by KangboLu** [comment]
Thank you for providing the feedback. At this point, we have submitted our milestone 4. We included the description of why we chose the median as the test flavor due to the skewness of distribution in the violin plots. For dependency, we don't include the yaml file because we use R mostly for analysis and didn't use conda.
